# Generated by Django 3.1.7 on 2021-06-28 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20210623_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=800),
        ),
    ]
