# Generated by Django 3.1.7 on 2021-04-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210427_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='default_phone_number',
        ),
    ]
