# Generated by Django 3.1.7 on 2021-04-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210428_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalAddress',
            new_name='DeliveryAddress',
        ),
    ]
