# Generated by Django 3.1.7 on 2021-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210430_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
