# Generated by Django 3.1.7 on 2021-06-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderlineitem_fabric_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='fabric_choice',
        ),
    ]
