# Generated by Django 3.1.7 on 2021-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
