# Generated by Django 3.1.7 on 2021-06-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_product_review'),
        ('review', '0002_review_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
