# Generated by Django 3.1.7 on 2021-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_product',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
