# Generated by Django 3.1.7 on 2021-04-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_display_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
