# Generated by Django 3.1.7 on 2021-05-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_custom_fabricchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricchoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fabricchoice',
            name='name',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
