# Generated by Django 3.1.7 on 2021-05-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_custom_has_nose_wire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
