# Generated by Django 3.1.7 on 2021-05-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210503_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='image',
        ),
        migrations.AddField(
            model_name='custom',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_type'),
        ),
    ]
