# Generated by Django 3.1.7 on 2021-05-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210503_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='display_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
