# Generated by Django 3.1.7 on 2021-05-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210503_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
