# Generated by Django 3.1.7 on 2021-05-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_custom_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
