# Generated by Django 3.1.7 on 2021-05-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_delete_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricchoice',
            name='display_name',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
