# Generated by Django 3.1.7 on 2021-05-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210522_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fabric_choice',
            new_name='has_fabric_choice',
        ),
    ]
