# Generated by Django 3.1.7 on 2021-06-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_orderlineitem_fabric_choice'),
        ('products', '0028_auto_20210522_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FabricChoice',
        ),
    ]
