# Generated by Django 3.1.7 on 2021-06-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
