# Generated by Django 3.1.7 on 2021-06-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_fabric_choice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
    ]
